FROM debian:jessie
MAINTAINER Matt McCormick "matt.mccormick@kitware.com"

RUN apt-get update && apt-get install -y curl && \\
  sed -i "s/httpredir.debian.org/`curl -s -D - http://httpredir.debian.org/demo/debian/ | awk '/^Link:/ { print $2 }' | sed -e 's@<http://\(.*\)/debian/>;@\1@g'`/" /etc/apt/sources.list

RUN apt-get update && apt-get -y install \\
  automake \\
  autogen \\
  bash \\
  build-essential \\
  bzip2 \\
  ca-certificates \\
  curl \\
  file \\
  git \\
  gzip \\
  libcurl4-openssl-dev \\
  libssl-dev \\
  make \\
  ncurses-dev \\
  pkg-config \\
  libtool \\
  python \\
  rsync \\
  sed \\
  bison \\
  flex \\
  tar \\
  vim \\
  wget \\
  runit \\
  xz-utils && \\
  apt-get -y clean

#include "common.docker"
