FROM emscripten/emsdk:2.0.34

LABEL maintainer="Matt McCormick matt.mccormick@kitware.com"

# Revert back to "/bin/sh" as default shell
# See https://github.com/asRIA/emscripten-docker/blob/master/Dockerfile.in#L4
RUN rm /bin/sh && ln -s /bin/dash /bin/sh

ARG DEBIAN_FRONTEND=noninteractive

RUN \
  apt-get update --yes && \
  apt-get install --no-install-recommends --yes \
    automake \
    autogen \
    bash \
    build-essential \
    bc \
    bzip2 \
    ca-certificates \
    curl \
    dirmngr \
    file \
    gettext \
    gnupg2 \
    gosu \
    gzip \
    zip \
    make \
    libncurses5 \
    ncurses-dev \
    pkg-config \
    libtool \
    python3 \
    python3-pip \
    osslsigncode \
    rsync \
    sed \
    ssh \
    bison \
    flex \
    tar \
    pax \
    vim \
    wget \
    xz-utils \
    zlib1g-dev \
  && \
  apt-get clean --yes

RUN ln -s /usr/bin/python3 /usr/bin/python

#include "common.dockcross"

#include "common.docker"

ENV EMSCRIPTEN_VERSION 2.0.34

ENV PATH /emsdk:/emsdk/upstream/bin/:/emsdk/upstream/emscripten:${PATH}
ENV CC=/emsdk/upstream/emscripten/emcc \
  CXX=/emsdk/upstream/emscripten/em++ \
  AR=/emsdk/upstream/emscripten/emar

RUN chmod -R 777 /emsdk/upstream/emscripten/cache

ENV CMAKE_TOOLCHAIN_FILE /emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake

#include "common.label-and-env"
