FROM dockcross/base:latest

LABEL maintainer="Matt McCormick matt.mccormick@kitware.com"

ENV WASI_VERSION 16
ENV WASI_VERSION_FULL ${WASI_VERSION}.0
RUN cd /usr/ && \
  curl -L -O https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_VERSION}/wasi-sdk-${WASI_VERSION_FULL}-linux.tar.gz && \
  tar xvzf wasi-sdk-${WASI_VERSION_FULL}-linux.tar.gz && \
  rm wasi-sdk-${WASI_VERSION_FULL}-linux.tar.gz
ENV WASI_SDK_PATH /usr/wasi-sdk-${WASI_VERSION_FULL}
ENV WASI_SYSROOT ${WASI_SDK_PATH}/share/wasi-sysroot

COPY clang-wasi-sysroot.sh clang++-wasi-sysroot.sh /usr/local/bin/

ENV CROSS_TRIPLE=wasm32-wasi
ENV CROSS_ROOT=${WASI_SDK_PATH}
ENV ANDROID_NDK=${CROSS_ROOT}
ENV AR=${CROSS_ROOT}/bin/llvm-ar \
    CC=clang-wasi-sysroot.sh \
    CXX=clang++-wasi-sysroot.sh \
    LD=${CROSS_ROOT}/bin/wasm-ld

#include "common.webassembly"

COPY WASI.cmake /usr/src/
RUN mv /usr/src/WASI.cmake /usr/share/cmake-*/Modules/Platform/
COPY *.cmake /usr/src/
RUN mv /usr/src/*.cmake /usr/share/cmake-*/Modules/
COPY CheckTypeSize.c.in /usr/src/
RUN mv /usr/src/CheckTypeSize.c.in /usr/share/cmake-*/Modules/
COPY Toolchain.cmake ${CROSS_ROOT}/
ENV CMAKE_TOOLCHAIN_FILE ${CROSS_ROOT}/Toolchain.cmake

#include "common.label-and-env"
